name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron:  '0 0 * * *'

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}    

env:
  COMPILE_JOBS: 2

jobs:
  build:
    name: Build ${{ matrix.build_type }}-dealii:${{ matrix.dealii_version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_type: ["Release"]
        dealii_version: ["master", "v9.3.0", "v9.2.0"]
    
    container:
      image: dealii/dealii:${{ matrix.dealii_version }}-focal

    steps:
      - name: Setup
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          
      - uses: actions/checkout@v2

      - name: Compile
        run: |
          mkdir build
          cd build
          cmake ../ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          make -j${{ env.COMPILE_JOBS }}
          
